spring:
  application:
    name: graphql-server
  graphql:
    graphiql:
      enabled: true
service:
  order:
    url: http://localhost:7070
  delivery:
    url: http://localhost:6060
server:
  max-http-request-header-size: 400000
  port: 8081
